package com.beans;
// Generated Mar 29, 2016 3:52:04 PM by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartId generated by hbm2java
 */
@Embeddable
public class CartId  implements java.io.Serializable {


     private Integer BId;
     private Integer CId;

    public CartId() {
    }

    public CartId(Integer BId, Integer CId) {
       this.BId = BId;
       this.CId = CId;
    }
   


    @Column(name="B_ID", nullable=false, precision=22, scale=0)
    public Integer getBId() {
        return this.BId;
    }
    
    public void setBId(Integer BId) {
        this.BId = BId;
    }


    @Column(name="C_ID", nullable=false, precision=22, scale=0)
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartId) ) return false;
		 CartId castOther = ( CartId ) other; 
         
		 return ( (this.getBId()==castOther.getBId()) || ( this.getBId()!=null && castOther.getBId()!=null && this.getBId().equals(castOther.getBId()) ) )
 && ( (this.getCId()==castOther.getCId()) || ( this.getCId()!=null && castOther.getCId()!=null && this.getCId().equals(castOther.getCId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBId() == null ? 0 : this.getBId().hashCode() );
         result = 37 * result + ( getCId() == null ? 0 : this.getCId().hashCode() );
         return result;
   }   


}


