package com.beans;
// Generated Mar 29, 2016 3:52:04 PM by Hibernate Tools 4.3.1



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="CART"
    ,schema="BOOKSTORE"
)
public class Cart  implements java.io.Serializable {


     private CartId id;
     private Book book;
     private Customer customer;
     private Integer CBCount;

    public Cart() {
    }

	
    public Cart(CartId id, Book book, Customer customer) {
        this.id = id;
        this.book = book;
        this.customer = customer;
    }
    public Cart(CartId id, Book book, Customer customer, Integer CBCount) {
       this.id = id;
       this.book = book;
       this.customer = customer;
       this.CBCount = CBCount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="BId", column=@Column(name="B_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="CId", column=@Column(name="C_ID", nullable=false, precision=22, scale=0) ) } )
    public CartId getId() {
        return this.id;
    }
    
    public void setId(CartId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="B_ID", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_ID", nullable=false, insertable=false, updatable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="C_B_COUNT", precision=22, scale=0)
    public Integer getCBCount() {
        return this.CBCount;
    }
    
    public void setCBCount(Integer CBCount) {
        this.CBCount = CBCount;
    }


//-------------------------------------------------
    
      public void addOnCount(int oldCount){
        CBCount+=oldCount;
        
                
    }

}


