package com.beans;
// Generated Mar 29, 2016 3:52:04 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OrderBook generated by hbm2java
 */
@Entity
@Table(name = "ORDER_BOOK", schema = "BOOKSTORE"
)
public class OrderBook implements java.io.Serializable {

    private Integer OBId;
    private Book book;
    private Orders orders;
    private Integer OBCount;

    public OrderBook() {
    }

    public OrderBook(Integer OBId, Book book, Orders orders) {
        this.OBId = OBId;
        this.book = book;
        this.orders = orders;
    }

    public OrderBook(Integer OBId, Book book, Orders orders, Integer OBCount) {
        this.OBId = OBId;
        this.book = book;
        this.orders = orders;
        this.OBCount = OBCount;
    }

    @Id
    @SequenceGenerator(name = "ORDER_BOOK_SEQ", sequenceName = "ORDER_BOOK_SEQ")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "ORDER_BOOK_SEQ")
    @Column(name = "O_B_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getOBId() {
        return this.OBId;
    }

    public void setOBId(Integer OBId) {
        this.OBId = OBId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "BOOK_ID", nullable = false)
    public Book getBook() {
        return this.book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORDER_NO")
    public Orders getOrders() {
        return this.orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @Column(name = "O_B_COUNT", precision = 22, scale = 0)
    public Integer getOBCount() {
        return this.OBCount;
    }

    public void setOBCount(Integer OBCount) {
        this.OBCount = OBCount;
    }

}
