package com.beans;
// Generated Mar 29, 2016 3:52:04 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS", schema = "BOOKSTORE"
)
public class Orders implements java.io.Serializable {

    private Integer orderId;
    private Customer customer;
    private Date orderDate;
    private Double total;
    private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public Orders() {
    }

    public Orders(Integer orderId) {
        this.orderId = orderId;
    }

    public Orders(Integer orderId, Customer customer, Date orderDate, Double total, Set<OrderBook> orderBooks) {
        this.orderId = orderId;
        this.customer = customer;
        this.orderDate = orderDate;
        this.total = total;
        this.orderBooks = orderBooks;
    }

    public Orders(Date orderDate, Double total, Set<OrderBook> orderBookList, Customer customer) {
        this.orderDate = orderDate;
        this.total = total;
        this.orderBooks = orderBookList;
        this.customer = customer;
    }

    @Id

    @Column(name = "ORDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMER_ID")
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ORDER_DATE", length = 7)
    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Column(name = "TOTAL", precision = 126, scale = 0)
    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }

    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }

}
